export const Buttons = [
  "Button Snippets",
  "Box-shadow Snippets",
  "Card Snippets",
  "Dropdown Snippets",
  "Input-fields Snippets",
  "Signup Snippets",
  "Login Snippets",
  "Radio Snippets",
  "Toggle Switches Snippets",
  "Page-Loader Snippets",
  "Text Snippets",
  "Checkbox Snippets",
  "Socials Snippets",
  "Form Snippets",
  "(Demo) Snippets",
];
