name: "📂 Blank Issue"
description: "Open a general issue without a specific template"
title: "[General] <short-title>"
labels: ["needs-triage"]
assignees: []


body:
  - type: dropdown
    id: category
    attributes:
      label: "📂 Category"
      options:
        - Enhancement
        - Refactor
        - Security
        - Design
        - Other


  - type: textarea
    id: context
    attributes:
      label: "📘 Additional Context (Optional)"
      description: "Add any other context, links, screenshots, or info that might be relevant."


  - type: checkboxes
    id: checklist
    attributes:
      label: "🙌 Contributor Checklist (Optional)"
      options:
        - label: "I have searched existing issues to avoid duplicates"
        - label: "I agree to follow this project's Code of Conduct"
        - label: "I am a GSSOC'25 contributor"
        - label: "I want to work on this issue"
