name: "🎨 UI/UX Suggestion"
description: "Suggest improvements for the user interface or experience"
title: "[UI/UX] <short-title>"
labels: ["design", "needs-triage"]
assignees: []

body:
  - type: textarea
    id: current
    attributes:
      label: "🖼️ Current UI/UX Behavior"
      description: "Describe how the interface currently behaves or looks."

  - type: textarea
    id: improvement
    attributes:
      label: "✨ Suggested Improvement"
      description: "What would you like to change or add?"

  - type: textarea
    id: visuals
    attributes:
      label: "📎 Screenshots / Visual Aids"
      description: "Mockups or screenshots help others understand your suggestion."

  - type: checkboxes
    id: checklist
    attributes:
      label: "🙌 Contributor Checklist"
      options:
        - label: "I agree to follow this project's Code of Conduct"
        - label: "I am a GSSOC'25 contributor"
        - label: "I want to work on this issue"
