export const Buttons = [
  "AvatarImage",
  "Animation",
  "BadgeSnippets",
  "Button Snippets",
  "Box-shadow Snippets",
  "Card Snippets",
  "Checkbox Snippets",
  "ColorPicker",
  "Coupon",
  "DarkMode",
  "(Demo) Snippets",
  "Dropdown Snippets",
  "Form Snippets",
  "FooterSnippets",
  "Input-fields Snippets",
  "Login Snippets",
  "Navbar-Icons",
  "NewsLetter",
  "Signup Snippets",
  "Pagination",
  "PaymentForm",
  "Page-Loader Snippets",
  "PillNavigation",
  "ProgressBar Snippets",
  "Responsiveness",
  "Radio Snippets",
  "SlideShow Snippets",
  "Sort",
  "Socials Snippets",
  "Toggle Switches Snippets",
  "Text Snippets",
  "Tables",
  "Shade",
];
